// Component
export { default as SimpleTable } from "./SimpleTable.svelte";

// Svelte-specific props and type overrides
export type {
  SimpleTableSvelteProps,
  TableInstance,
  SvelteHeaderObject,
  SvelteColumnEditorConfig,
  SvelteCellRenderer,
  SvelteHeaderRenderer,
  SvelteFooterRenderer,
  SvelteHeaderDropdown,
  SvelteColumnEditorRowRenderer,
  SvelteColumnEditorCustomRenderer,
  SvelteLoadingStateRenderer,
  SvelteErrorStateRenderer,
  SvelteEmptyStateRenderer,
} from "./types";

// Re-export vanilla types consumers need when building column definitions,
// callbacks, or using the imperative ref API.
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  BoundingBox,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorRowRendererComponents,
  ColumnEditorCustomRenderer,
  ColumnEditorCustomRendererProps,
  ColumnEditorRowRendererProps,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  DragHandlerProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  FooterRendererProps,
  GetRowId,
  GetRowIdParams,
  HeaderDropdown,
  HeaderDropdownProps,
  HeaderObject,
  HeaderRenderer,
  HeaderRendererComponents,
  HeaderRendererProps,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  OnSortProps,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowState,
  SetHeaderRenameProps,
  SharedTableProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  TableAPI,
  TableFilterState,
  TableHeaderProps,
  TableRowProps,
  Theme,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";
