// Component
export { default as SimpleTable } from "./SimpleTable.svelte";
export { asRows } from "simple-table-core";

// Svelte-specific props and type overrides
export type {
  SimpleTableSvelteProps,
  TableInstance,
  SvelteHeaderObject,
  SvelteIconsConfig,
  SvelteIconElement,
  SvelteColumnEditorConfig,
  SvelteCellRenderer,
  SvelteHeaderRenderer,
  SvelteFooterRenderer,
  SvelteHeaderDropdown,
  SvelteColumnEditorRowRenderer,
  SvelteColumnEditorCustomRenderer,
  SvelteRowButton,
  SvelteLoadingStateRenderer,
  SvelteErrorStateRenderer,
  SvelteEmptyStateRenderer,
} from "./types";

// Re-export vanilla types consumers need when building column definitions,
// callbacks, or using the imperative ref API.
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  AnimationsConfig,
  AutoSizeMode,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRenderer,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorRowRendererComponents,
  ColumnEditorCustomRenderer,
  ColumnEditorCustomRendererProps,
  ColumnEditorRowRendererProps,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  FilterOperator,
  StringFilterOperator,
  NumberFilterOperator,
  BooleanFilterOperator,
  DateFilterOperator,
  EnumFilterOperator,
  FooterRendererProps,
  FooterPosition,
  GetRowId,
  GetRowIdParams,
  HeaderDropdown,
  HeaderDropdownProps,
  HeaderObject,
  HeaderRenderer,
  HeaderRendererComponents,
  HeaderRendererProps,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  Pinned,
  PinnedSectionsState,
  PivotConfig,
  PivotValueConfig,
  PivotResult,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowSelectionMode,
  RowState,
  SetHeaderRenameProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  TableAPI,
  TableFilterState,
  TableRow,
  Theme,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";

export {
  pivotRows,
  buildPivotAccessor,
  buildPivotRowTotalAccessor,
  PIVOT_CHILDREN_KEY,
  PIVOT_IS_TOTAL_KEY,
  PIVOT_ACCESSOR_PREFIX,
  PIVOT_BLANK_LABEL,
} from "simple-table-core";
