// Component
export { default as SimpleTable } from "./SimpleTable";
export { asRows } from "simple-table-core";

// React-specific props and type overrides
export type {
  SimpleTableReactProps,
  TableInstance,
  ReactColumnDef,
  NestedReactColumnDef,
  NestedTableReactConfig,
  ReactColumnEditorConfig,
  ReactIconsConfig,
  ReactIconElement,
  ReactCellRenderer,
  ReactHeaderRenderer,
  ReactFooterRenderer,
  ReactHeaderDropdown,
  ReactColumnEditorRowRenderer,
  ReactColumnEditorCustomRenderer,
  ReactRowButton,
  ReactLoadingStateRenderer,
  ReactErrorStateRenderer,
  ReactEmptyStateRenderer,
  ReactDefaultRowData,
  HeaderRendererComponents,
  HeaderRendererProps,
  ColumnEditorRowRendererComponents,
  ColumnEditorRowRendererProps,
  ColumnEditorCustomRendererProps,
  FooterRendererProps,
  HeaderDropdownProps,
} from "./types";

// Re-export vanilla types for callbacks and the imperative ref API. For
// column definitions and column-related callbacks on `SimpleTable`, use
// `ReactColumnDef` (exported above).
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  AnimationsConfig,
  AutoSizeMode,
  ColumnDef,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRenderer,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorCustomRenderer,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  FilterOperator,
  StringFilterOperator,
  NumberFilterOperator,
  BooleanFilterOperator,
  DateFilterOperator,
  EnumFilterOperator,
  FooterPosition,
  GetRowId,
  GetRowIdParams,
  GetRowClass,
  GetRowClassParams,
  HeaderDropdown,
  HeaderRenderer,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  Pinned,
  PinnedSectionsState,
  PivotConfig,
  PivotValueConfig,
  PivotResult,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowData,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowSelectionMode,
  RowState,
  SetHeaderRenameProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  // TableAPI is the type consumers use for useRef<TableAPI>(null)
  TableAPI,
  TableFilterState,
  TableRow,
  Theme,
  TdgpAggregation,
  TdgpAggregationFn,
  TdgpFilterGroup,
  TdgpFilterModel,
  TdgpFilterNot,
  TdgpFilterOperator,
  TdgpFilterPredicate,
  TdgpGroupNode,
  TdgpQueryClient,
  TdgpQueryRequest,
  TdgpQueryResponse,
  TdgpTableProps,
  TdgpTableSnapshot,
  TdgpTableSource,
  TdgpTableSourceOptions,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";

export {
  pivotRows,
  buildPivotAccessor,
  buildPivotRowTotalAccessor,
  PIVOT_IS_TOTAL_KEY,
  PIVOT_ACCESSOR_PREFIX,
  PIVOT_BLANK_LABEL,
  createTdgpTableSource,
  tableFiltersToTdgpFilter,
  tableFilterConditions,
  sortColumnToTdgpSort,
  isTdgpGroupNode,
  tdgpGroupNodeToRow,
  tdgpGroupNodesToRows,
  getTdgpGroupKeys,
  setNestedChildren,
  TDGP_CHILDREN_ACCESSOR,
  TDGP_GROUP_KEYS,
} from "simple-table-core";

export { useTdgpTable } from "./tdgp/useTdgpTable";
export type { UseTdgpTableOptions } from "./tdgp/useTdgpTable";
