// Component
export { default as SimpleTable } from "./SimpleTable";
export { asRows } from "simple-table-core";

// Vue-specific props and type overrides
export type {
  SimpleTableVueProps,
  TableInstance,
  VueColumnDef,
  VueColumnEditorConfig,
  VueIconsConfig,
  VueIconElement,
  VueCellRenderer,
  VueHeaderRenderer,
  VueFooterRenderer,
  VueHeaderDropdown,
  VueColumnEditorRowRenderer,
  VueColumnEditorCustomRenderer,
  VueRowButton,
  VueLoadingStateRenderer,
  VueErrorStateRenderer,
  VueEmptyStateRenderer,
} from "./types";

// Re-export vanilla types consumers need when building column definitions,
// callbacks, or using the imperative ref API.
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  AnimationsConfig,
  AutoSizeMode,
  ColumnDef,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRenderer,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorRowRendererComponents,
  ColumnEditorCustomRenderer,
  ColumnEditorCustomRendererProps,
  ColumnEditorRowRendererProps,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  FilterOperator,
  StringFilterOperator,
  NumberFilterOperator,
  BooleanFilterOperator,
  DateFilterOperator,
  EnumFilterOperator,
  FooterRendererProps,
  FooterPosition,
  GetRowId,
  GetRowIdParams,
  HeaderDropdown,
  HeaderDropdownProps,
  HeaderRenderer,
  HeaderRendererComponents,
  HeaderRendererProps,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  Pinned,
  PinnedSectionsState,
  PivotConfig,
  PivotValueConfig,
  PivotResult,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowSelectionMode,
  RowState,
  SetHeaderRenameProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  TableAPI,
  TableFilterState,
  TableRow,
  Theme,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";

export {
  pivotRows,
  buildPivotAccessor,
  buildPivotRowTotalAccessor,
  PIVOT_CHILDREN_KEY,
  PIVOT_IS_TOTAL_KEY,
  PIVOT_ACCESSOR_PREFIX,
  PIVOT_BLANK_LABEL,
} from "simple-table-core";
