// Component
export { SimpleTable } from "./SimpleTable";
export { asRows } from "simple-table-core";

// Solid-specific props and type overrides
export type {
  SimpleTableSolidProps,
  TableInstance,
  SolidHeaderObject,
  SolidColumnEditorConfig,
  SolidIconsConfig,
  SolidIconElement,
  SolidCellRenderer,
  SolidHeaderRenderer,
  SolidFooterRenderer,
  SolidHeaderDropdown,
  SolidColumnEditorRowRenderer,
  SolidColumnEditorCustomRenderer,
  SolidRowButton,
  SolidLoadingStateRenderer,
  SolidErrorStateRenderer,
  SolidEmptyStateRenderer,
} from "./types";

// Re-export vanilla types consumers need when building column definitions,
// callbacks, or using the imperative ref API.
export type {
  Accessor,
  AggregationConfig,
  AggregationType,
  BoundingBox,
  Cell,
  CellChangeProps,
  CellClickProps,
  CellRenderer,
  CellRendererProps,
  CellValue,
  ChartOptions,
  ColumnEditorConfig,
  ColumnEditorRowRenderer,
  ColumnEditorRowRendererComponents,
  ColumnEditorCustomRenderer,
  ColumnEditorCustomRendererProps,
  ColumnEditorRowRendererProps,
  ColumnEditorSearchFunction,
  ColumnType,
  ColumnVisibilityState,
  Comparator,
  ComparatorProps,
  CustomTheme,
  CustomThemeProps,
  DragHandlerProps,
  EmptyStateRenderer,
  EmptyStateRendererProps,
  EnumOption,
  ErrorStateRenderer,
  ErrorStateRendererProps,
  ExportToCSVProps,
  ExportValueGetter,
  ExportValueProps,
  FilterCondition,
  FilterOperator,
  StringFilterOperator,
  NumberFilterOperator,
  BooleanFilterOperator,
  DateFilterOperator,
  EnumFilterOperator,
  FooterRendererProps,
  GetRowId,
  GetRowIdParams,
  HeaderDropdown,
  HeaderDropdownProps,
  HeaderObject,
  HeaderRenderer,
  HeaderRendererComponents,
  HeaderRendererProps,
  IconsConfig,
  LoadingStateRenderer,
  LoadingStateRendererProps,
  OnRowGroupExpandProps,
  OnSortProps,
  PivotConfig,
  PivotValueConfig,
  PivotResult,
  QuickFilterConfig,
  QuickFilterGetter,
  QuickFilterGetterProps,
  QuickFilterMode,
  Row,
  RowButtonProps,
  RowId,
  RowSelectionChangeProps,
  RowState,
  SetHeaderRenameProps,
  SharedTableProps,
  ShowWhen,
  SimpleTableConfig,
  SimpleTableProps,
  SortColumn,
  TableAPI,
  TableFilterState,
  TableHeaderProps,
  TableRowProps,
  Theme,
  UpdateDataProps,
  ValueFormatter,
  ValueFormatterProps,
  ValueGetter,
  ValueGetterProps,
} from "simple-table-core";

export {
  pivotRows,
  buildPivotAccessor,
  buildPivotRowTotalAccessor,
  PIVOT_CHILDREN_KEY,
  PIVOT_IS_TOTAL_KEY,
  PIVOT_ACCESSOR_PREFIX,
  PIVOT_BLANK_LABEL,
} from "simple-table-core";
