import HeaderObject from "../types/HeaderObject";

export const SAMPLE_HEADERS: HeaderObject[] = [
  {
    label: "Product ID",
    accessor: "productId",
    width: 100,
    isSortable: true,
    isEditable: true,
    type: "string",
  },
  {
    accessor: "productName",
    isSortable: true,
    isEditable: true,
    label: "Product Name",
    width: 100,
  },
  {
    label: "Category",
    accessor: "category",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Quantity",
    accessor: "quantity",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Price",
    accessor: "price",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Supplier",
    accessor: "supplier",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Location",
    accessor: "location",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Reorder Level",
    accessor: "reorderLevel",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "SKU",
    accessor: "sku",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Description",
    accessor: "description",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Weight",
    accessor: "weight",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Dimensions",
    accessor: "dimensions",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Barcode",
    accessor: "barcode",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  {
    label: "Expiration Date",
    accessor: "expirationDate",
    width: 100,
    isSortable: true,
    isEditable: true,
  },
  { label: "Manufacturer", accessor: "manufacturer", width: 100 },
];

// export const SAMPLE_HEADERS: HeaderObject[] = [
//   {
//     label: "Product ID",
//     accessor: "productId",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//     type: "string",
//   },
//   {
//     accessor: "productName",
//     isSortable: true,
//     isEditable: true,
//     label: "Product Name",
//     width: 200,
//   },
//   {
//     label: "Category",
//     accessor: "category",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Quantity",
//     accessor: "quantity",
//     width: 100,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Price",
//     accessor: "price",
//     width: 100,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Supplier",
//     accessor: "supplier",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Location",
//     accessor: "location",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Reorder Level",
//     accessor: "reorderLevel",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "SKU",
//     accessor: "sku",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Description",
//     accessor: "description",
//     width: 250,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Weight",
//     accessor: "weight",
//     width: 100,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Dimensions",
//     accessor: "dimensions",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Barcode",
//     accessor: "barcode",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   {
//     label: "Expiration Date",
//     accessor: "expirationDate",
//     width: 150,
//     isSortable: true,
//     isEditable: true,
//   },
//   { label: "Manufacturer", accessor: "manufacturer", width: 150 },
// ];

export const inventoryData: any[] = Array.from({ length: 50 }, (_, index) => ({
  productId: `P-${index + 1001}`,
  productName: [
    "Wireless Mouse",
    "Bluetooth Speaker",
    "LED Monitor",
    "Gaming Keyboard",
    "Smartphone",
    "Laptop",
    "Tablet",
    "Headphones",
    "Smartwatch",
    "External Hard Drive",
  ][index % 10],
  category: ["Electronics", "Furniture", "Clothing", "Food", "Books"][
    Math.floor(Math.random() * 5)
  ],
  quantity: Math.floor(Math.random() * 100) + 1,
  price: (Math.random() * 100).toFixed(2),
  supplier: [
    "Tech Supplies Co.",
    "Gadget World",
    "Office Essentials",
    "Home Comforts",
    "Fashion Hub",
  ][Math.floor(Math.random() * 5)],
  location: [
    "Warehouse A - New York",
    "Warehouse B - Los Angeles",
    "Warehouse C - Chicago",
    "Warehouse D - Houston",
    "Warehouse E - Miami",
  ][Math.floor(Math.random() * 5)],
  reorderLevel: Math.floor(Math.random() * 20) + 5,
  sku: `SKU-${index + 1001}`,
  description: `High-quality ${
    [
      "wireless mouse",
      "bluetooth speaker",
      "LED monitor",
      "gaming keyboard",
      "smartphone",
      "laptop",
      "tablet",
      "headphones",
      "smartwatch",
      "external hard drive",
    ][index % 10]
  } for everyday use.`,
  weight: `${(Math.random() * 10).toFixed(2)} kg`,
  dimensions: `${(Math.random() * 100).toFixed(2)}x${(
    Math.random() * 100
  ).toFixed(2)}x${(Math.random() * 100).toFixed(2)} cm`,
  barcode: `1234567890${index}`,
  expirationDate: `2024-${Math.floor(Math.random() * 12) + 1}-${
    Math.floor(Math.random() * 28) + 1
  }`,
  manufacturer: [
    "Tech Innovators Inc.",
    "Gadget Makers Ltd.",
    "Office Producers",
    "Home Creators",
    "Fashion Designers",
  ][Math.floor(Math.random() * 5)],
}));
