import SimpleTable from "../../../components/simple-table/SimpleTable";
import { HeaderObject } from "../../..";

const headers: HeaderObject[] = [
  { accessor: "organization", label: "Organization", width: 200, expandable: true, type: "string" },
  { accessor: "employees", label: "Employees", width: 100, type: "number" },
  { accessor: "budget", label: "Annual Budget", width: 140, type: "string" },
  { accessor: "performance", label: "Performance", width: 120, type: "string" },
  { accessor: "location", label: "Location", width: 130, type: "string" },
  { accessor: "growthRate", label: "Growth", width: 90, type: "string" },
  { accessor: "status", label: "Status", width: 110, type: "string" },
  { accessor: "established", label: "Est. Date", width: 110, type: "date" },
];

// In the new format, we have a flat array where grouping is defined by the 'divisions' and 'teams' properties
// The rowGrouping prop will tell the table how to group: ["divisions", "teams"]
const rows = [
  // TechSolutions Inc. company
  {
    id: 1,
    organization: "TechSolutions Inc.",
    employees: 137,
    budget: "$15.0M",
    performance: "Exceeding",
    location: "San Francisco",
    growthRate: "+9%",
    status: "Expanding",
    established: "2018-01-01",
    divisions: [
      {
        id: 101,
        organization: "Engineering",
        employees: 97,
        budget: "$10.6M",
        performance: "Exceeding",
        location: "Multiple",
        growthRate: "+11%",
        status: "Expanding",
        established: "2018-01-15",
        teams: [
          {
            id: 1001,
            organization: "Frontend",
            employees: 28,
            budget: "$2.8M",
            performance: "Exceeding",
            location: "San Francisco",
            growthRate: "+12%",
            status: "Hiring",
            established: "2019-05-16",
          },
          {
            id: 1002,
            organization: "Backend",
            employees: 32,
            budget: "$3.4M",
            performance: "Meeting",
            location: "Seattle",
            growthRate: "+8%",
            status: "Stable",
            established: "2018-03-22",
          },
          {
            id: 1003,
            organization: "DevOps",
            employees: 15,
            budget: "$1.9M",
            performance: "Exceeding",
            location: "Remote",
            growthRate: "+15%",
            status: "Hiring",
            established: "2020-11-05",
          },
          {
            id: 1004,
            organization: "Mobile",
            employees: 22,
            budget: "$2.5M",
            performance: "Meeting",
            location: "Austin",
            growthRate: "+10%",
            status: "Restructuring",
            established: "2019-08-12",
          },
        ],
      },
      {
        id: 102,
        organization: "Product",
        employees: 40,
        budget: "$4.4M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+5%",
        status: "Stable",
        established: "2019-01-10",
        teams: [
          {
            id: 1101,
            organization: "Design",
            employees: 17,
            budget: "$1.8M",
            performance: "Meeting",
            location: "Portland",
            growthRate: "+6%",
            status: "Stable",
            established: "2019-02-28",
          },
          {
            id: 1102,
            organization: "Research",
            employees: 9,
            budget: "$1.4M",
            performance: "Below Target",
            location: "Boston",
            growthRate: "+3%",
            status: "Reviewing",
            established: "2020-07-15",
          },
          {
            id: 1103,
            organization: "QA Testing",
            employees: 14,
            budget: "$1.2M",
            performance: "Meeting",
            location: "Chicago",
            growthRate: "+5%",
            status: "Stable",
            established: "2019-11-01",
          },
        ],
      },
    ],
  },
  // HealthFirst Group company
  {
    id: 2,
    organization: "HealthFirst Group",
    employees: 138,
    budget: "$22.4M",
    performance: "Meeting",
    location: "Boston",
    growthRate: "+8%",
    status: "Stable",
    established: "2010-01-01",
    divisions: [
      {
        id: 201,
        organization: "Hospital Operations",
        employees: 106,
        budget: "$13.1M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+6%",
        status: "Expanding",
        established: "2010-01-05",
        teams: [
          {
            id: 2001,
            organization: "Emergency",
            employees: 48,
            budget: "$5.2M",
            performance: "Meeting",
            location: "New York",
            growthRate: "+4%",
            status: "Critical",
            established: "2010-06-14",
          },
          {
            id: 2002,
            organization: "Cardiology",
            employees: 32,
            budget: "$4.8M",
            performance: "Exceeding",
            location: "Chicago",
            growthRate: "+9%",
            status: "Expanding",
            established: "2012-03-25",
          },
          {
            id: 2003,
            organization: "Pediatrics",
            employees: 26,
            budget: "$3.1M",
            performance: "Meeting",
            location: "Boston",
            growthRate: "+7%",
            status: "Stable",
            established: "2014-08-30",
          },
        ],
      },
      {
        id: 202,
        organization: "Research & Development",
        employees: 32,
        budget: "$9.3M",
        performance: "Exceeding",
        location: "Multiple",
        growthRate: "+15%",
        status: "Hiring",
        established: "2017-01-10",
        teams: [
          {
            id: 2101,
            organization: "Clinical Trials",
            employees: 18,
            budget: "$4.2M",
            performance: "Exceeding",
            location: "San Diego",
            growthRate: "+12%",
            status: "Expanding",
            established: "2017-04-18",
          },
          {
            id: 2102,
            organization: "Genomics",
            employees: 14,
            budget: "$5.1M",
            performance: "Exceeding",
            location: "Cambridge",
            growthRate: "+18%",
            status: "Hiring",
            established: "2019-02-21",
          },
        ],
      },
    ],
  },
  // Global Finance company
  {
    id: 3,
    organization: "Global Finance",
    employees: 121,
    budget: "$15.5M",
    performance: "Meeting",
    location: "New York",
    growthRate: "+3%",
    status: "Restructuring",
    established: "2005-01-01",
    divisions: [
      {
        id: 301,
        organization: "Banking Operations",
        employees: 121,
        budget: "$15.5M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+3%",
        status: "Stable",
        established: "2005-01-15",
        teams: [
          {
            id: 3001,
            organization: "Retail Banking",
            employees: 56,
            budget: "$4.8M",
            performance: "Meeting",
            location: "New York",
            growthRate: "+2%",
            status: "Stable",
            established: "2005-11-08",
          },
          {
            id: 3002,
            organization: "Investment",
            employees: 38,
            budget: "$7.2M",
            performance: "Exceeding",
            location: "Chicago",
            growthRate: "+11%",
            status: "Hiring",
            established: "2008-05-12",
          },
          {
            id: 3003,
            organization: "Loans",
            employees: 27,
            budget: "$3.5M",
            performance: "Below Target",
            location: "Dallas",
            growthRate: "-3%",
            status: "Restructuring",
            established: "2010-03-17",
          },
        ],
      },
    ],
  },
  // Apex University
  {
    id: 4,
    organization: "Apex University",
    employees: 115,
    budget: "$13.4M",
    performance: "Meeting",
    location: "Cambridge",
    growthRate: "+6%",
    status: "Stable",
    established: "1992-01-01",
    divisions: [
      {
        id: 401,
        organization: "Academic Departments",
        employees: 115,
        budget: "$13.4M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+6%",
        status: "Stable",
        established: "1992-01-15",
        teams: [
          {
            id: 4001,
            organization: "Computer Science",
            employees: 35,
            budget: "$3.8M",
            performance: "Meeting",
            location: "Boston",
            growthRate: "+8%",
            status: "Expanding",
            established: "1998-08-24",
          },
          {
            id: 4002,
            organization: "Business",
            employees: 42,
            budget: "$4.5M",
            performance: "Exceeding",
            location: "Chicago",
            growthRate: "+6%",
            status: "Stable",
            established: "1995-09-15",
          },
          {
            id: 4003,
            organization: "Engineering",
            employees: 38,
            budget: "$5.1M",
            performance: "Meeting",
            location: "San Francisco",
            growthRate: "+4%",
            status: "Stable",
            established: "1992-02-11",
          },
        ],
      },
    ],
  },
  // Industrial Systems
  {
    id: 5,
    organization: "Industrial Systems",
    employees: 152,
    budget: "$12.9M",
    performance: "Meeting",
    location: "Detroit",
    growthRate: "+3%",
    status: "Stable",
    established: "2001-01-01",
    divisions: [
      {
        id: 501,
        organization: "Production",
        employees: 152,
        budget: "$12.9M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+3%",
        status: "Stable",
        established: "2001-01-10",
        teams: [
          {
            id: 5001,
            organization: "Assembly",
            employees: 78,
            budget: "$6.2M",
            performance: "Meeting",
            location: "Detroit",
            growthRate: "+2%",
            status: "Stable",
            established: "2001-05-18",
          },
          {
            id: 5002,
            organization: "Quality Control",
            employees: 32,
            budget: "$2.8M",
            performance: "Exceeding",
            location: "Pittsburgh",
            growthRate: "+5%",
            status: "Hiring",
            established: "2003-11-24",
          },
          {
            id: 5003,
            organization: "Logistics",
            employees: 42,
            budget: "$3.9M",
            performance: "Meeting",
            location: "Indianapolis",
            growthRate: "+3%",
            status: "Stable",
            established: "2005-02-08",
          },
        ],
      },
    ],
  },
  // Creative Media
  {
    id: 6,
    organization: "Creative Media",
    employees: 154,
    budget: "$28.5M",
    performance: "Exceeding",
    location: "Los Angeles",
    growthRate: "+14%",
    status: "Expanding",
    established: "2008-01-01",
    divisions: [
      {
        id: 601,
        organization: "Studio Operations",
        employees: 154,
        budget: "$28.5M",
        performance: "Exceeding",
        location: "Multiple",
        growthRate: "+14%",
        status: "Expanding",
        established: "2008-01-15",
        teams: [
          {
            id: 6001,
            organization: "Production",
            employees: 64,
            budget: "$12.5M",
            performance: "Exceeding",
            location: "Los Angeles",
            growthRate: "+15%",
            status: "Expanding",
            established: "2008-07-22",
          },
          {
            id: 6002,
            organization: "Post-Production",
            employees: 38,
            budget: "$8.2M",
            performance: "Meeting",
            location: "Vancouver",
            growthRate: "+9%",
            status: "Hiring",
            established: "2010-04-15",
          },
          {
            id: 6003,
            organization: "Animation",
            employees: 52,
            budget: "$7.8M",
            performance: "Exceeding",
            location: "San Francisco",
            growthRate: "+18%",
            status: "Expanding",
            established: "2014-09-30",
          },
        ],
      },
    ],
  },
  // ShopSmart
  {
    id: 7,
    organization: "ShopSmart",
    employees: 155,
    budget: "$10.5M",
    performance: "Below Target",
    location: "Chicago",
    growthRate: "+2%",
    status: "Restructuring",
    established: "2009-01-01",
    divisions: [
      {
        id: 701,
        organization: "Store Operations",
        employees: 155,
        budget: "$10.5M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+7%",
        status: "Stable",
        established: "2009-01-05",
        teams: [
          {
            id: 7001,
            organization: "Sales",
            employees: 85,
            budget: "$4.2M",
            performance: "Below Target",
            location: "Multiple",
            growthRate: "-2%",
            status: "Restructuring",
            established: "2009-03-14",
          },
          {
            id: 7002,
            organization: "Customer Support",
            employees: 42,
            budget: "$2.8M",
            performance: "Meeting",
            location: "Phoenix",
            growthRate: "+1%",
            status: "Stable",
            established: "2010-11-22",
          },
          {
            id: 7003,
            organization: "Online Store",
            employees: 28,
            budget: "$3.5M",
            performance: "Exceeding",
            location: "Remote",
            growthRate: "+22%",
            status: "Expanding",
            established: "2018-06-05",
          },
        ],
      },
    ],
  },
  // Green Harvest
  {
    id: 8,
    organization: "Green Harvest",
    employees: 116,
    budget: "$12.8M",
    performance: "Meeting",
    location: "Iowa",
    growthRate: "+4%",
    status: "Stable",
    established: "2005-01-01",
    divisions: [
      {
        id: 801,
        organization: "Farming Operations",
        employees: 116,
        budget: "$12.8M",
        performance: "Meeting",
        location: "Multiple",
        growthRate: "+4%",
        status: "Stable",
        established: "2005-01-10",
        teams: [
          {
            id: 8001,
            organization: "Crop Division",
            employees: 56,
            budget: "$5.1M",
            performance: "Meeting",
            location: "Iowa",
            growthRate: "+4%",
            status: "Stable",
            established: "2005-02-18",
          },
          {
            id: 8002,
            organization: "Livestock",
            employees: 42,
            budget: "$4.8M",
            performance: "Below Target",
            location: "Nebraska",
            growthRate: "-1%",
            status: "Reviewing",
            established: "2007-05-22",
          },
          {
            id: 8003,
            organization: "Research",
            employees: 18,
            budget: "$2.9M",
            performance: "Exceeding",
            location: "California",
            growthRate: "+9%",
            status: "Expanding",
            established: "2015-08-11",
          },
        ],
      },
    ],
  },
];

const RowGroupingExample = () => {
  return (
    <div style={{ padding: "2rem" }}>
      <SimpleTable
        columnResizing
        defaultHeaders={headers}
        rows={rows}
        rowGrouping={["divisions", "teams"]}
        rowIdAccessor="id"
        height="calc(100dvh - 112px)"
      />
    </div>
  );
};

export default RowGroupingExample;
