import HeaderObject from "../../../types/HeaderObject";

export const EMPLOYEE_HEADERS: HeaderObject[] = [
  {
    accessor: "name",
    label: "Full Name",
    width: 180,
    type: "string",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "email",
    label: "Email Address",
    width: 220,
    type: "string",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "department",
    label: "Department",
    width: 150,
    type: "enum",
    enumOptions: [
      { label: "Engineering", value: "Engineering" },
      { label: "Product", value: "Product" },
      { label: "Marketing", value: "Marketing" },
      { label: "Sales", value: "Sales" },
      { label: "Customer Support", value: "Customer Support" },
      { label: "HR", value: "HR" },
      { label: "Finance", value: "Finance" },
      { label: "Operations", value: "Operations" },
    ],
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "position",
    label: "Position",
    width: 180,
    type: "string",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "salary",
    label: "Annual Salary",
    width: 140,
    type: "number",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "hireDate",
    label: "Hire Date",
    width: 140,
    type: "date",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "performanceReview",
    label: "Last Review",
    width: 140,
    type: "date",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "rating",
    label: "Rating",
    width: 100,
    type: "number",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "isActive",
    label: "Active Employee",
    width: 140,
    type: "boolean",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "isRemote",
    label: "Remote Worker",
    width: 140,
    type: "boolean",
    isEditable: true,
    isSortable: true,
  },
  {
    accessor: "projectsCompleted",
    label: "Completed Projects",
    width: 160,
    type: "number",
    isEditable: true,
    isSortable: true,
  },
];
